
create table #nomops(strnombre varchar(250))

INSERT #nomops (strnombre)
values ('Recorte de modelo')
,('Zocalo')
,('Delimitar dado')
,('Scannear')
,('Diseñar')
,('Fresar')
,('Sinterizar')
,('Montar porcelana')
,('Colocación de wash')
,('Ajustar')
,('Glacear y samblastear')
,('Recorte de modelo')
,('Zocalo')
,('Delimitar dado')
,('Scannear')
,('Diseñar')
,('Fresar')
,('Sinterizar')
,('Ajustar en modelo')
,('Samblastear')
,('Glacear')
,('Recorte de modelo')
,('Zocalo')
,('Delimitar dado')
,('Scannear')
,('Diseñar')
,('Fresar')
,('Sinterizar')
,('Montar porcelana')
,('Colocación de wash')
,('Ajustar')
,('Glacear y samblastear')
,('Recorte de modelo')
,('Zocalo')
,('Delimitar dado')
,('Scanear')
,('Diseñar')
,('Articular')
,('Imprimir estructura')
,('Lavar estructurs')
,('Fotocurar estructura')
,('Revisar estructura en modelo')
,('Colocar cueles')
,('Colocar en cubilete')
,('Revesti cubiete')
,('Meter en horno desencerado')
,('Vaciar metal cubilete')
,('Rescatar cubilete')
,('Cortar cueles')
,('Ajustar metales')
,('Samblastear metales')
,('Lavar y colocar en ultrasonido')
,('Recorte de modelo')
,('Zocalo')
,('Delimitar dado')
,('Scanear')
,('Diseñar')
,('Articular')
,('Imprimir estructura')
,('Lavar estructurs')
,('Fotocurar estructura')
,('Revisar estructura en modelo')
,('Colocar cueles')
,('Colocar en cubilete')
,('Revesti cubiete')
,('Meter en horno desencerado')
,('Vaciar metal cubilete')
,('Rescatar cubilete')
,('Cortar cueles')
,('Ajustar metales')
,('Samblastear metales')
,('Lavar y colocar en ultrasonido')
,('Colocar cueles')
,('Cubilete')
,('Revestir')
,('Desencerar')
,('Vaciar metal en cubilete')
,('Rescatar cubilete')
,('Cortar cueles')
,('Samblastear')
,('Recorte de modelo')
,('Zocalo')
,('Delimitar dado')
,('Scanear')
,('Diseñar')
,('Articular')
,('Imprimir estructura')
,('Lavar estructurs')
,('Fotocurar estructura')
,('Revisar estructura en modelo')
,('Colocar cueles')
,('Colocar en cubilete')
,('Revesti cubiete')
,('Meter en horno desencerado')
,('Vaciar metal cubilete')
,('Rescatar cubilete')
,('Cortar cueles')
,('Ajustar metales')
,('Samblastear metales')
,('Lavar y colocar en ultrasonido')
,('Recorte modelos')
,('Zocalo')
,('Delimitar dado')
,('Scannear')
,('Diseñar')
,('Articular')
,('Imprimir estructura')
,('Lavar estructura')
,('Fotocurar estructura')
,('Revisar estructura en modelo')
,('Colocar cueles')
,('Colocar cubilete')
,('Revestir cubilete')
,('Meter en horno desencerado')
,('Vaciar metal en cubilete')
,('Rescatar cubilete')
,('Cortar cueles')
,('Ajustar metales')
,('Samblastear metales')
,('Lavar y colocar en ultrasonido')
,('Colocar bond ')
,('Opacar')
,('Montaje de porcelana')
,('Ajustar  ')
,('Glacear')
,('Encia')
,('Recorte modelos')
,('Zocalo')
,('Cortar aditamento o calcinable')
,('Scannear')
,('Diseñar')
,('Articular')
,('Imprimir estructura')
,('Lavar estructura')
,('Fotocurar estructura')
,('Revisar estructura en modelo')
,('Colocar cueles')
,('Colocar en cubilete')
,('Revestir cubiletes')
,('Desencerar')
,('Vacia metal en cubilete')
,('Rescatar cubilete')
,('Cortar cueles')
,('Ajustar metales en aditamento')
,('Samblastear metal')
,('Lavar y colocar en ultrasonido')
,('Colocar bond')
,('Opacar')
,('Montaje porcelana')
,('Ajustar  ')
,('Glacear')
,('Pulir parte escpuesta')
,('Samblastear  ')
,('Recorte modelos')
,('Zocalo')
,('Delimitar dado')
,('Scannear')
,('Diseñar')
,('Articular')
,('Imprimir estructura')
,('Lavar estructura')
,('Fotocurar estructura')
,('Revisar estructura en modelo')
,('Colocar cueles')
,('Colocar cubilete')
,('Revestir cubilete')
,('Meter en horno desencerado')
,('Vaciar metal en cubilete')
,('Rescatar cubilete')
,('Cortar cueles')
,('Ajustar metales')
,('Samblastear metales')
,('Lavar y colocar en ultrasonido')
,('Colocar bond ')
,('Opacar')
,('Montaje de porcelana para encia')
,('Ajustar  ')
,('Glacear')
,('Recortar modelo')
,('Zocalo')
,('Delimitar dado')
,('Scannear')
,('Diseñar')
,('Articular')
,('Imprimir estructua')
,('Lavar estructura')
,('Fotocurar estructura')
,('Revisar estructura en modelo')
,('Colocar cueles')
,('Colocar en cubilete')
,('Revestir cubilete')
,('Meter a horno desencerado')
,('Inyectado')
,('Rescate de cubilete')
,('Colocar el acido')
,('Ajustar en modelo')
,('Samblastear')
,('Lavar   ')
,('Colocación de glass')
,('Montar porcelana')
,('Ajustar   ')
,('Glacear')
,('Samblastear')
,('Recortar modelo')
,('Zocalo')
,('Delimitar dado')
,('Scannear')
,('Diseñar')
,('Articular')
,('Imprimir estructua')
,('Lavar estructura')
,('Fotocurar estructura')
,('Revisar estructura en modelo')
,('Colocar cueles')
,('Colocar en cubilete')
,('Revestir cubilete')
,('Meter a horno desencerado')
,('Inyectado')
,('Rescate de cubilete')
,('Colocar el acido')
,('Ajustar en modelo')
,('Samblastear')
,('Lavar   ')
,('Colocación de glass')
,('Ajustar   ')
,('Glacear')
,('Samblastear')
,('Recortar modelo')
,('Zocalo')
,('Delimitar dado')
,('Scannear')
,('Diseñar')
,('Articular')
,('Imprimir estructua')
,('Lavar estructura')
,('Fotocurar estructura')
,('Revisar estructura en modelo')
,('Colocar cueles')
,('Colocar en cubilete')
,('Revestir cubilete')
,('Meter a horno desencerado')
,('Inyectado')
,('Rescate de cubilete')
,('Colocar el acido')
,('Ajustar en modelo')
,('Samblastear')
,('Lavar   ')
,('Colocación de glass')
,('Montar porcelana')
,('Ajustar   ')
,('Glacear')
,('Samblastear')
,('Recorte modelos')
,('Zocalo')
,('Delimitar dado')
,('Scannear')
,('Diseñar')
,('Articular')
,('Imprimir estructura')
,('Lavar estructura')
,('Fotocurar estructura')
,('Revisar estructura en modelo')
,('Colocar cueles')
,('Colocar cubilete')
,('Revestir cubilete')
,('Meter en horno desencerado')
,('Vaciar metal en cubilete')
,('Rescatar cubilete')
,('Cortar cueles')
,('Ajustar metales')
,('Samblastear metales')
,('Lavar y colocar en ultrasonido')
,('Colocar bond ')
,('Opacar')
,('Montaje de porcelana para encia')
,('Ajustar  ')
,('Glacear')
,('Recortar modelo')
,('Zocalo')
,('Delimitar dado')
,('Colocar separador')
,('Hacer corona en resina')
,('Se mete a cocer al horno')
,('Ajustar')
,('Pulir')
,('Samblastear')
,('Recortar modelo')
,('Zocalo')
,('Delimitar dado')
,('Colocar separador')
,('Hacer corona en resina')
,('Se mete a cocer al horno')
,('Ajustar')
,('Pulir')
,('Samblastear')
,('Recortar modelo')
,('Zocalo')
,('Delimitar dado')
,('Colocar separador')
,('Hacer corona en resina')
,('Se mete a cocer al horno')
,('Ajustar')
,('Pulir')
,('Samblastear')
,('Recortar modelo')
,('Zocalo')
,('Prepara modelo')
,('Encerar')


SELECT 'INSERT tbOperacion([strNombre],[strNombreCorto], strUsuarioAlta, strMaquinaAlta, datFechaAlta) SELECT '+''''+strnombre+''''+', '+''''+'PENDIENTE'+''''+', strUsuarioAlta = '+''''+'MR-JOC'+''''+', strMaquinaAlta = '+''''+'127.0.0.1'+''''+', datFechaAlta = GETDATE()'
	,strnombre
FROM #nomops
GROUP BY strnombre

DROP TABLE #nomops


